[versions]
androidsdk-compile = "33"
androidsdk-target = "33"
androidsdk-min = "26"

kotlin = "1.7.10"
ksp = "1.7.10-1.0.6"
ktlint = "0.43.2"
coroutines = "1.6.4"
androidx-activity = "1.5.1"
androidx-compose-compiler = "1.3.1"
androidx-compose = "1.2.0-beta03"
androidx-lifecycle = "2.5.1"
androidx-navigation = "2.5.1"
hilt = "2.43.2"
hilt-workManager = "1.0.0"
glide = "4.13.0"
okio = "3.0.0"
okhttp = "4.9.0"
moshi = "1.13.0"
epoxy = "4.3.1"
autovalue = "1.9"
retrofit = "2.9.0"
accompanist = "0.23.0"
agp = "7.2.2"
kotlin1710 = "1.7.10"
core-ktx = "1.9.0"
kotlin-bom = "1.8.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
compose-bom = "2023.03.00"

[libraries]
android-gradle = "com.android.tools.build:gradle:7.2.2"

coreLibraryDesugaring = "com.android.tools:desugar_jdk_libs:1.1.5"

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-androidExtensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-reflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-rx = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "coroutines" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.3.0"
androidx-core-testing = "androidx.arch.core:core-testing:2.1.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.5.0"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-datastore = "androidx.datastore:datastore-preferences:1.0.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.5.2"
androidx-mediarouter = "androidx.mediarouter:mediarouter:1.2.6"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-transition = "androidx.transition:transition-ktx:1.4.1"
androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.1.0-beta01"

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha03"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.4.0-beta02"

androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

androidx-hilt-navigationFragment = "androidx.hilt:hilt-navigation-fragment:1.0.0"

androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
androidx-navigation-commonktx = { module = "androidx.navigation:navigation-common-ktx", version.ref = "androidx-navigation" }

gson = "com.google.code.gson:gson:2.8.8"
installreferrer = "com.android.installreferrer:installreferrer:1.0"
javax-inject = "javax.inject:javax.inject:1"
jsc = "org.webkit:android-jsc:+"
json = "org.json:json:20190722"
lottie = "com.airbnb.android:lottie:5.1.1"
material = "com.google.android.material:material:1.3.0"

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-response-modeling = "com.slack.eithernet:eithernet:1.4.1"

hilt = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-workManager = { module = "androidx.hilt:hilt-work", version.ref = "hilt-workManager" }
hilt-workManager-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-workManager" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide-okhttp = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-urlConnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshi-reflection = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }

store = "com.github.mobilenativefoundation:store:36a548b"

coil = "io.coil-kt:coil-compose:2.2.2"

# Workmanager
workManager = "androidx.work:work-runtime-ktx:2.7.1"

#biometrics
biometric = "androidx.biometric:biometric:1.2.0-alpha05"

# Test dependencies
junit = "junit:junit:4.12"
mockk = "io.mockk:mockk:1.12.4"
turbine = "app.cash.turbine:turbine:0.8.0"
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin-bom" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
com-google-android-material-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }

[bundles]
androidx-compose-debug = [
    "androidx-activity-compose",
    "androidx-viewmodel-compose",
    "androidx-compose-compiler",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling",
    "androidx-compose-foundation",
    "androidx-compose-material"
]
androidx-compose = [
    "androidx-activity-compose",
    "androidx-viewmodel-compose",
    "androidx-compose-compiler",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-foundation",
    "androidx-compose-material"
]
[plugins]
spotless = "com.diffplug.spotless:6.1.0"
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin1710" }
androidApplication = { id = "com.android.application", version.ref = "agp" }